### ISSUE TITLE
Problème de fixation de l'éclairage

### ISSUE THREAD

**Issue by ghost** [Artilect-BioTronic/phytotron-rpi#2]
La fixation à la colle à chaud ne fonctionne pas.

Je propose de fixer les 4 panneaux de LED sur une plaque de plexiglas pliée de façon à reposer d'un côté sur le bloc "lumière/thermostat" du frigo et de l'autre sur le premier rail en haut.

Mesure et dessin de la plaque de plexi, découpe laser puis thermopliage

**Comment by ghost** [comment]
Plexiglas transparent ou translucide (diffusion...) ?

**Comment by Fabrizzio-ATA** [comment]
Translucide c'est bien... :-)                                                                                                                                     Je t'ai laissé 1 feuille avec 1 imprimé du schéma d'architecture et une proposition de fixation des LEDS :- fixer des "rails" en plexis au plafond du frigo pour glisser les plaques  Led à l'interieur...- si tu poses les LEDS sur le plexi, ne risque-t-il pas de chauffer/brûler ? ‎- j'aime bien l'idée de diffuseur et encore mieux si on peut confiner et contrôler la chaleur des LEDs                                                                                                                                                                                                   _____________Fabrice Galinier‎Bonne journée - Have a nice day - Guten Tag - Selamat Pagi - Jo Napot - Kalimera                                                                                                                                                                                                                De: arofarnEnvoyé: mardi 14 novembre 2017 16:57À: Artilect-BioTronic/phytotron-rpiRépondre à: Artilect-BioTronic/phytotron-rpiCc: SubscribedObjet: Re: [Artilect-BioTronic/phytotron-rpi] Problème de fixation de l'éclairage (#2)Plexiglas transparent ou translucide (diffusion...) ?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Artilect-BioTronic/phytotron-rpi","title":"Artilect-BioTronic/phytotron-rpi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Artilect-BioTronic/phytotron-rpi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@arofarn in #2: Plexiglas transparent ou translucide (diffusion...) ?"}],"action":{"name":"View Issue","url":"https://github.com/Artilect-BioTronic/phytotron-rpi/issues/2#issuecomment-344304307"}}}

**Comment by ghost** [comment]
Je n'ai pas encore dessiner ce que j'ai en tête, mais en schema ça donne:

- plafond du phytotron
- 0.5 à 1cm d'air
- panneau de LED sur entretoises
- air
- support en plexi
- enceinte de culture

Vu le peu de puissance, je pense que ce sera suffisant pour éviter tout problème de chauffe. En plus, je ne pense pas faire un truc "étanche" vis à vis du reste de l'enceinte.

En bonus, on peu prévoir un emplacement au centre pour une camera de raspberry pi (option, car ce ne sera pas toujours le bon angle de vu)

**Comment by ghost** [comment]
Résolu à 95%
Il reste à faire une petite cale (je 'en occupe)

**Comment by ghost** [comment]
Câles posées.
