### ISSUE TITLE
Ajout de pieds ou roulettes

### ISSUE THREAD

**Issue by ghost** [Artilect-BioTronic/phytotron-rpi#5]
Pour surélever un peu le phytotron posé au sol.

Préférence pour des roulettes qui facilitent le transport. Si roulette, penser à en prendre 2 avec frein.

=> libère aussi la table à roulette.

**Comment by Fabrizzio-ATA** [comment]
Table roulettes 20€ 400kghttps://www.manomano.fr/autre-support-2313?model_id=1069941&referer_id=537135&ach=2f8ed&achsqrt=c4a77&gclid=EAIaIQobChMIxIK8vbi-1wIVRbobCh3ttQnaEAQYBCABEgKjiPD_BwE                                                                                                                                                                                                                                                                                                                                        _____________Fabrice GalinierBonne journée - Have a nice day - Guten Tag - Selamat Pagi - Jo Napot - Kalimera                                                                                                                                                                                                                De: arofarnEnvoyé: mardi 14 novembre 2017 17:02À: Artilect-BioTronic/phytotron-rpiRépondre à: Artilect-BioTronic/phytotron-rpiCc: SubscribedObjet: [Artilect-BioTronic/phytotron-rpi] Ajout de pieds ou roulettes (#5)Pour surélever un peu le phytotron posé au sol.
Préférence pour des roulettes qui facilitent le transport. Si roulette, penser à en prendre 2 avec frein.
=> libère aussi la table à roulette.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Artilect-BioTronic/phytotron-rpi","title":"Artilect-BioTronic/phytotron-rpi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Artilect-BioTronic/phytotron-rpi"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Ajout de pieds ou roulettes (#5)"}],"action":{"name":"View Issue","url":"https://github.com/Artilect-BioTronic/phytotron-rpi/issues/5"}}}

**Comment by ghost** [comment]
Un plateau n'étais pas forcément le plus pratique. Et à une semaine de Futurapolis, ça devient joueur de passer des commande sur internet. En plus, c'est le bon moment pour le montage : le phytotron est vide et facile à retourner.

=> J'ai acheté et monté (avec Arnaud et Yohann) des roulettes de 75mm. Comme prévu, 2 ont des freins.
