### ISSUE TITLE
Renfort de l'étagère en plexi 

### ISSUE THREAD

**Issue by ghost** [Artilect-BioTronic/phytotron-rpi#6]
L'étagère en plexi commence à fléchir après quelques mois d'usage.

Je propose un renfort avec une cornière en aluminium coté fond. J'ai ce qu'il faut à la maison.

**Comment by Fabrizzio-ATA** [comment]
Comment tu la fixes ? Pkoi pas une baguette alu transversale sous l'etagere ?                                                                                                                                                                                                                                                                                                                                         _____________Fabrice GalinierBonne journée - Have a nice day - Guten Tag - Selamat Pagi - Jo Napot - Kalimera                                                                                                                                                                                                                De: arofarnEnvoyé: mardi 14 novembre 2017 17:04À: Artilect-BioTronic/phytotron-rpiRépondre à: Artilect-BioTronic/phytotron-rpiCc: SubscribedObjet: [Artilect-BioTronic/phytotron-rpi] Renfort de l'étagère en plexi (#6)L'étagère en plexi commence à fléchir après quelques mois d'usage.
Je propose un renfort avec une cornière en aluminium coté fond. J'ai ce qu'il faut à la maison.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Artilect-BioTronic/phytotron-rpi","title":"Artilect-BioTronic/phytotron-rpi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Artilect-BioTronic/phytotron-rpi"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Renfort de l'étagère en plexi  (#6)"}],"action":{"name":"View Issue","url":"https://github.com/Artilect-BioTronic/phytotron-rpi/issues/6"}}}

**Comment by ghost** [comment]
Fixation par collage ou vissage sous l'étagère au fond.

**Comment by ghost** [comment]
Au final, j'ai découpé un peu juste et le profilé en alu rentre avec une légère pressions sur les paroies qui sont un peu souples (j'ai été surpris).

Du coup, pas besoin de fixation pour l'instant. A voir à l'usage si la fixation est nécessaire. L'avantage de ne pas coller ou viser l'étagère et le profilé : plus facile de nettoyer les salissure entre les deux éléments.
