### ISSUE TITLE
Nettoyage et désinfection

### ISSUE THREAD

**Issue by ghost** [Artilect-BioTronic/phytotron-rpi#8]
Profiter du démontage de l'électronique pour un gros nettoyage et une désinfection de l'enceinte de culture.

Il y a eu des problèmes important de contamination lors des dernières manip' avec les mycélium.

**Comment by Fabrizzio-ATA** [comment]
Et un pti cadenas à code pour fermer la porte ? Ce serait bien de faire ca pour les autres frigos du Fablab et éviter des ouvertures intempestives...‎ Je peux acheter des cadenas si vous voulez                                                                                                                                                                                                   _____________Fabrice GalinierBonne journée - Have a nice day - Guten Tag - Selamat Pagi - Jo Napot - Kalimera                                                                                                                                                                                                                De: arofarnEnvoyé: mardi 14 novembre 2017 17:15À: Artilect-BioTronic/phytotron-rpiRépondre à: Artilect-BioTronic/phytotron-rpiCc: SubscribedObjet: [Artilect-BioTronic/phytotron-rpi] Nettoyage et désinfection (#8)Profiter du démontage de l'électronique pour un gros nettoyage et une désinfection de l'enceinte de culture.
Il y a eu des problèmes important de contamination lors des dernières manip' avec les mycélium.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Artilect-BioTronic/phytotron-rpi","title":"Artilect-BioTronic/phytotron-rpi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Artilect-BioTronic/phytotron-rpi"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Nettoyage et désinfection (#8)"}],"action":{"name":"View Issue","url":"https://github.com/Artilect-BioTronic/phytotron-rpi/issues/8"}}}

**Comment by ghost** [comment]
Bonne idée mais voir https://github.com/Artilect-BioTronic/phytotron-rpi/issues/4 ;)

**Comment by ghost** [comment]
Nettoyage terminé :)
